apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bl27x569d-go
  janus-idp.io/tekton: bl27x569d-go
  backstage.io/kubernetes-id: bl27x569d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bl27x569d-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
